// generated with @7nohe/openapi-react-query-codegen@2.1.0 

import { useMutation, UseMutationOptions, useQuery, UseQueryOptions } from "@tanstack/react-query";
import type { Options } from "../requests/sdk.gen";
import { getDebugInfo, getSession, login, signup } from "../requests/sdk.gen";
import { GetDebugInfoData, GetSessionData, LoginData, SignupData } from "../requests/types.gen";
import * as Common from "./common";
export const useGetSession = <TData = Common.GetSessionDefaultResponse, TError = unknown, TQueryKey extends Array<unknown> = unknown[]>(clientOptions: Options<GetSessionData, true> = {}, queryKey?: TQueryKey, options?: Omit<UseQueryOptions<TData, TError>, "queryKey" | "queryFn">) => useQuery<TData, TError>({ queryKey: Common.UseGetSessionKeyFn(clientOptions, queryKey), queryFn: () => getSession({ ...clientOptions }).then(response => response.data as TData) as TData, ...options });
export const useGetDebugInfo = <TData = Common.GetDebugInfoDefaultResponse, TError = unknown, TQueryKey extends Array<unknown> = unknown[]>(clientOptions: Options<GetDebugInfoData, true> = {}, queryKey?: TQueryKey, options?: Omit<UseQueryOptions<TData, TError>, "queryKey" | "queryFn">) => useQuery<TData, TError>({ queryKey: Common.UseGetDebugInfoKeyFn(clientOptions, queryKey), queryFn: () => getDebugInfo({ ...clientOptions }).then(response => response.data as TData) as TData, ...options });
export const useSignup = <TData = Common.SignupMutationResult, TError = unknown, TQueryKey extends Array<unknown> = unknown[], TContext = unknown>(mutationKey?: TQueryKey, options?: Omit<UseMutationOptions<TData, TError, Options<SignupData, true>, TContext>, "mutationKey" | "mutationFn">) => useMutation<TData, TError, Options<SignupData, true>, TContext>({ mutationKey: Common.UseSignupKeyFn(mutationKey), mutationFn: clientOptions => signup(clientOptions) as unknown as Promise<TData>, ...options });
export const useLogin = <TData = Common.LoginMutationResult, TError = unknown, TQueryKey extends Array<unknown> = unknown[], TContext = unknown>(mutationKey?: TQueryKey, options?: Omit<UseMutationOptions<TData, TError, Options<LoginData, true>, TContext>, "mutationKey" | "mutationFn">) => useMutation<TData, TError, Options<LoginData, true>, TContext>({ mutationKey: Common.UseLoginKeyFn(mutationKey), mutationFn: clientOptions => login(clientOptions) as unknown as Promise<TData>, ...options });
