// This file is auto-generated by @hey-api/openapi-ts

export const SignupRequestDtoSchema = {
    type: 'object',
    properties: {
        name: {
            type: 'string'
        },
        username: {
            type: 'string'
        },
        password: {
            type: 'string'
        },
        passwordConfirmation: {
            type: 'string'
        }
    },
    required: [
        'name',
        'username',
        'password',
        'passwordConfirmation'
    ]
} as const;

export const SignupResponseDtoSchema = {
    type: 'object',
    properties: {
        accessToken: {
            type: 'string'
        }
    },
    required: [
        'accessToken'
    ]
} as const;

export const LoginRequestDtoSchema = {
    type: 'object',
    properties: {
        username: {
            type: 'string'
        },
        password: {
            type: 'string'
        }
    },
    required: [
        'username',
        'password'
    ]
} as const;

export const LoginResponseDtoSchema = {
    type: 'object',
    properties: {
        accessToken: {
            type: 'string'
        }
    },
    required: [
        'accessToken'
    ]
} as const;

export const SessionResponseDtoSchema = {
    type: 'object',
    properties: {
        id: {
            type: 'string'
        },
        username: {
            type: 'string'
        }
    },
    required: [
        'id',
        'username'
    ]
} as const;
